site_name: stephanie isan 
site_url: https://stephanieisan.com
dev_addr: 127.0.0.1:8001
plugins: []
nav:
  - home: index.md
  - about: about.md
  - publications & honors: publications.md
  - contact: contact.md
extra:
  generator: false
extra_javascript:
  - https://code.jquery.com/jquery-2.2.4.js
  - https://code.jquery.com/ui/1.12.1/jquery-ui.js
  - scripts/extras.js
extra_css:
  - stylesheets/tooltips.css
  - stylesheets/contact-form.css
  - stylesheets/animations.css
  - stylesheets/extras.css
markdown_extensions:
    - meta
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - attr_list
    - md_in_html
theme:
  name: material
  logo: assets/hot-sauce.png
  favicon: assets/boba.png
  features:
    - header.autohide
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night 
        name: switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: switch to light mode
